# Generated by Django 3.0.1 on 2021-09-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
